[package]
name = "convex_types"
version = "0.1.0"
authors = ["Convex, Inc. <no-reply@convex.dev>"]
edition = "2024"
license = "LicenseRef-FSL-1.1-Apache-2.0"
description = "Shared types for Convex to avoid circular dependencies"

[lib]
doctest = false

[features]
testing = ["proptest", "proptest-derive"]

[dependencies]
serde = { workspace = true }

# Optional testing dependencies
proptest = { workspace = true, optional = true }
proptest-derive = { workspace = true, optional = true }

[dev-dependencies]
proptest = { workspace = true }
proptest-derive = { workspace = true }

[lints]
workspace = true
